### PR TITLE
Ajaxed favbutton oldhandler

### PR DESCRIPTION
**Pull request by nugged**
Renewal of my previous try, but in this time there is no need to modification in Act itself,
on my test vagrant/Act it works with clean Act (actdev branch, which set as preset in alexm/Act-vagrant).

All those round "Art"-buttons to make talk favorite now work in ajax-mode,
in talks list, and in single talk screen.

If anything needed, any corrections from me, I am available in hangouts (nugged@gmail.com).

### CODE REVIEW

**Comment by vrivas** [comment]
Really nice, Andrew.
Thanks a lot!

**Comment by vrivas** [comment]
There is only a problem I've noticed: when viewing the details of talk, if you press the round Art-button, the list of attendants does not shows the change.
To be honest, I am not 100% sure if the previous version did this in an correct way, but I think ti did.
Could you try to fix this, Andrew?

**Comment by nugged** [comment]
looking now

**Comment by nugged** [comment]
@vrivas, https://github.com/Act-Conferences/ye2015/pull/22

**Pull request merged**
